/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../../common";

export interface OCR2AbstractInterface extends utils.Interface {
  functions: {
    "latestConfigDetails()": FunctionFragment;
    "latestConfigDigestAndEpoch()": FunctionFragment;
    "setConfig(address[],address[],uint8,bytes,uint64,bytes)": FunctionFragment;
    "transmit(bytes32[3],bytes,bytes32[],bytes32[],bytes32)": FunctionFragment;
    "typeAndVersion()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "latestConfigDetails"
      | "latestConfigDigestAndEpoch"
      | "setConfig"
      | "transmit"
      | "typeAndVersion"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "latestConfigDetails",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "latestConfigDigestAndEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transmit",
    values: [
      [
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>
      ],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "typeAndVersion",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "latestConfigDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestConfigDigestAndEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transmit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "typeAndVersion",
    data: BytesLike
  ): Result;

  events: {
    "ConfigSet(uint32,bytes32,uint64,address[],address[],uint8,bytes,uint64,bytes)": EventFragment;
    "Transmitted(bytes32,uint32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ConfigSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transmitted"): EventFragment;
}

export interface ConfigSetEventObject {
  previousConfigBlockNumber: number;
  configDigest: string;
  configCount: BigNumber;
  signers: string[];
  transmitters: string[];
  f: number;
  onchainConfig: string;
  offchainConfigVersion: BigNumber;
  offchainConfig: string;
}
export type ConfigSetEvent = TypedEvent<
  [
    number,
    string,
    BigNumber,
    string[],
    string[],
    number,
    string,
    BigNumber,
    string
  ],
  ConfigSetEventObject
>;

export type ConfigSetEventFilter = TypedEventFilter<ConfigSetEvent>;

export interface TransmittedEventObject {
  configDigest: string;
  epoch: number;
}
export type TransmittedEvent = TypedEvent<
  [string, number],
  TransmittedEventObject
>;

export type TransmittedEventFilter = TypedEventFilter<TransmittedEvent>;

export interface OCR2Abstract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OCR2AbstractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    latestConfigDetails(
      overrides?: CallOverrides
    ): Promise<
      [number, number, string] & {
        configCount: number;
        blockNumber: number;
        configDigest: string;
      }
    >;

    latestConfigDigestAndEpoch(
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, number] & {
        scanLogs: boolean;
        configDigest: string;
        epoch: number;
      }
    >;

    setConfig(
      signers: PromiseOrValue<string>[],
      transmitters: PromiseOrValue<string>[],
      f: PromiseOrValue<BigNumberish>,
      onchainConfig: PromiseOrValue<BytesLike>,
      offchainConfigVersion: PromiseOrValue<BigNumberish>,
      offchainConfig: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transmit(
      reportContext: [
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>
      ],
      report: PromiseOrValue<BytesLike>,
      rs: PromiseOrValue<BytesLike>[],
      ss: PromiseOrValue<BytesLike>[],
      rawVs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    typeAndVersion(overrides?: CallOverrides): Promise<[string]>;
  };

  latestConfigDetails(
    overrides?: CallOverrides
  ): Promise<
    [number, number, string] & {
      configCount: number;
      blockNumber: number;
      configDigest: string;
    }
  >;

  latestConfigDigestAndEpoch(
    overrides?: CallOverrides
  ): Promise<
    [boolean, string, number] & {
      scanLogs: boolean;
      configDigest: string;
      epoch: number;
    }
  >;

  setConfig(
    signers: PromiseOrValue<string>[],
    transmitters: PromiseOrValue<string>[],
    f: PromiseOrValue<BigNumberish>,
    onchainConfig: PromiseOrValue<BytesLike>,
    offchainConfigVersion: PromiseOrValue<BigNumberish>,
    offchainConfig: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transmit(
    reportContext: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ],
    report: PromiseOrValue<BytesLike>,
    rs: PromiseOrValue<BytesLike>[],
    ss: PromiseOrValue<BytesLike>[],
    rawVs: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  typeAndVersion(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    latestConfigDetails(
      overrides?: CallOverrides
    ): Promise<
      [number, number, string] & {
        configCount: number;
        blockNumber: number;
        configDigest: string;
      }
    >;

    latestConfigDigestAndEpoch(
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, number] & {
        scanLogs: boolean;
        configDigest: string;
        epoch: number;
      }
    >;

    setConfig(
      signers: PromiseOrValue<string>[],
      transmitters: PromiseOrValue<string>[],
      f: PromiseOrValue<BigNumberish>,
      onchainConfig: PromiseOrValue<BytesLike>,
      offchainConfigVersion: PromiseOrValue<BigNumberish>,
      offchainConfig: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    transmit(
      reportContext: [
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>
      ],
      report: PromiseOrValue<BytesLike>,
      rs: PromiseOrValue<BytesLike>[],
      ss: PromiseOrValue<BytesLike>[],
      rawVs: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    typeAndVersion(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ConfigSet(uint32,bytes32,uint64,address[],address[],uint8,bytes,uint64,bytes)"(
      previousConfigBlockNumber?: null,
      configDigest?: null,
      configCount?: null,
      signers?: null,
      transmitters?: null,
      f?: null,
      onchainConfig?: null,
      offchainConfigVersion?: null,
      offchainConfig?: null
    ): ConfigSetEventFilter;
    ConfigSet(
      previousConfigBlockNumber?: null,
      configDigest?: null,
      configCount?: null,
      signers?: null,
      transmitters?: null,
      f?: null,
      onchainConfig?: null,
      offchainConfigVersion?: null,
      offchainConfig?: null
    ): ConfigSetEventFilter;

    "Transmitted(bytes32,uint32)"(
      configDigest?: null,
      epoch?: null
    ): TransmittedEventFilter;
    Transmitted(configDigest?: null, epoch?: null): TransmittedEventFilter;
  };

  estimateGas: {
    latestConfigDetails(overrides?: CallOverrides): Promise<BigNumber>;

    latestConfigDigestAndEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    setConfig(
      signers: PromiseOrValue<string>[],
      transmitters: PromiseOrValue<string>[],
      f: PromiseOrValue<BigNumberish>,
      onchainConfig: PromiseOrValue<BytesLike>,
      offchainConfigVersion: PromiseOrValue<BigNumberish>,
      offchainConfig: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transmit(
      reportContext: [
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>
      ],
      report: PromiseOrValue<BytesLike>,
      rs: PromiseOrValue<BytesLike>[],
      ss: PromiseOrValue<BytesLike>[],
      rawVs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    typeAndVersion(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    latestConfigDetails(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    latestConfigDigestAndEpoch(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setConfig(
      signers: PromiseOrValue<string>[],
      transmitters: PromiseOrValue<string>[],
      f: PromiseOrValue<BigNumberish>,
      onchainConfig: PromiseOrValue<BytesLike>,
      offchainConfigVersion: PromiseOrValue<BigNumberish>,
      offchainConfig: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transmit(
      reportContext: [
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>
      ],
      report: PromiseOrValue<BytesLike>,
      rs: PromiseOrValue<BytesLike>[],
      ss: PromiseOrValue<BytesLike>[],
      rawVs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    typeAndVersion(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
