/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuthorizedOriginReceiverInterface } from "./AuthorizedOriginReceiverInterface";
export type { AuthorizedReceiverInterface } from "./AuthorizedReceiverInterface";
export type { FunctionsBillingRegistryInterface } from "./FunctionsBillingRegistryInterface";
export type { FunctionsClientInterface } from "./FunctionsClientInterface";
export type { FunctionsOracleInterface } from "./FunctionsOracleInterface";
