/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ERC677ReceiverInterface,
  ERC677ReceiverInterfaceInterface,
} from "../../../../../../@chainlink/contracts/src/v0.8/interfaces/ERC677ReceiverInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onTokenTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ERC677ReceiverInterface__factory {
  static readonly abi = _abi;
  static createInterface(): ERC677ReceiverInterfaceInterface {
    return new utils.Interface(_abi) as ERC677ReceiverInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC677ReceiverInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC677ReceiverInterface;
  }
}
