/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OCR2Base__factory } from "./OCR2Base__factory";
export { OCR2BaseUpgradeable__factory } from "./OCR2BaseUpgradeable__factory";
