/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dev from "./dev";
export type { dev };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { AutomationBase } from "./AutomationBase";
export type { AutomationCompatible } from "./AutomationCompatible";
export type { ConfirmedOwner } from "./ConfirmedOwner";
export type { ConfirmedOwnerWithProposal } from "./ConfirmedOwnerWithProposal";
