/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as functions from "./functions";
export type { functions };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as ocr2 from "./ocr2";
export type { ocr2 };
import type * as vendor from "./vendor";
export type { vendor };
export type { AuthorizedReceiver } from "./AuthorizedReceiver";
