/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  FunctionsBillingRegistryInterface,
  FunctionsBillingRegistryInterfaceInterface,
} from "../../../../contracts/dev/interfaces/FunctionsBillingRegistryInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "gasLimit",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "gasPrice",
        type: "uint256",
      },
      {
        internalType: "uint96",
        name: "donFee",
        type: "uint96",
      },
      {
        internalType: "uint96",
        name: "registryFee",
        type: "uint96",
      },
    ],
    name: "estimateCost",
    outputs: [
      {
        internalType: "uint96",
        name: "",
        type: "uint96",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "response",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "err",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "transmitter",
        type: "address",
      },
      {
        internalType: "address[31]",
        name: "signers",
        type: "address[31]",
      },
      {
        internalType: "uint8",
        name: "signerCount",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "reportValidationGas",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "initialGas",
        type: "uint256",
      },
    ],
    name: "fulfillAndBill",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getRequestConfig",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        components: [
          {
            internalType: "uint64",
            name: "subscriptionId",
            type: "uint64",
          },
          {
            internalType: "address",
            name: "client",
            type: "address",
          },
          {
            internalType: "uint32",
            name: "gasLimit",
            type: "uint32",
          },
          {
            internalType: "uint256",
            name: "gasPrice",
            type: "uint256",
          },
        ],
        internalType: "struct FunctionsBillingRegistryInterface.RequestBilling",
        name: "billing",
        type: "tuple",
      },
    ],
    name: "getRequiredFee",
    outputs: [
      {
        internalType: "uint96",
        name: "",
        type: "uint96",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "subscriptionId",
        type: "uint64",
      },
    ],
    name: "getSubscriptionOwner",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        components: [
          {
            internalType: "uint64",
            name: "subscriptionId",
            type: "uint64",
          },
          {
            internalType: "address",
            name: "client",
            type: "address",
          },
          {
            internalType: "uint32",
            name: "gasLimit",
            type: "uint32",
          },
          {
            internalType: "uint256",
            name: "gasPrice",
            type: "uint256",
          },
        ],
        internalType: "struct FunctionsBillingRegistryInterface.RequestBilling",
        name: "billing",
        type: "tuple",
      },
    ],
    name: "startBilling",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class FunctionsBillingRegistryInterface__factory {
  static readonly abi = _abi;
  static createInterface(): FunctionsBillingRegistryInterfaceInterface {
    return new utils.Interface(
      _abi
    ) as FunctionsBillingRegistryInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FunctionsBillingRegistryInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as FunctionsBillingRegistryInterface;
  }
}
