/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OCR2Base } from "./OCR2Base";
export type { OCR2BaseUpgradeable } from "./OCR2BaseUpgradeable";
