/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface OCR2BaseUpgradeableInterface extends utils.Interface {
  functions: {
    "acceptOwnership()": FunctionFragment;
    "latestConfigDetails()": FunctionFragment;
    "latestConfigDigestAndEpoch()": FunctionFragment;
    "owner()": FunctionFragment;
    "setConfig(address[],address[],uint8,bytes,uint64,bytes)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transmit(bytes32[3],bytes,bytes32[],bytes32[],bytes32)": FunctionFragment;
    "transmitters()": FunctionFragment;
    "typeAndVersion()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptOwnership"
      | "latestConfigDetails"
      | "latestConfigDigestAndEpoch"
      | "owner"
      | "setConfig"
      | "transferOwnership"
      | "transmit"
      | "transmitters"
      | "typeAndVersion"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "latestConfigDetails",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "latestConfigDigestAndEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transmit",
    values: [
      [
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>
      ],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transmitters",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "typeAndVersion",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestConfigDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestConfigDigestAndEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transmit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transmitters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "typeAndVersion",
    data: BytesLike
  ): Result;

  events: {
    "ConfigSet(uint32,bytes32,uint64,address[],address[],uint8,bytes,uint64,bytes)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferRequested(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Transmitted(bytes32,uint32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ConfigSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transmitted"): EventFragment;
}

export interface ConfigSetEventObject {
  previousConfigBlockNumber: number;
  configDigest: string;
  configCount: BigNumber;
  signers: string[];
  transmitters: string[];
  f: number;
  onchainConfig: string;
  offchainConfigVersion: BigNumber;
  offchainConfig: string;
}
export type ConfigSetEvent = TypedEvent<
  [
    number,
    string,
    BigNumber,
    string[],
    string[],
    number,
    string,
    BigNumber,
    string
  ],
  ConfigSetEventObject
>;

export type ConfigSetEventFilter = TypedEventFilter<ConfigSetEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferRequestedEventObject {
  from: string;
  to: string;
}
export type OwnershipTransferRequestedEvent = TypedEvent<
  [string, string],
  OwnershipTransferRequestedEventObject
>;

export type OwnershipTransferRequestedEventFilter =
  TypedEventFilter<OwnershipTransferRequestedEvent>;

export interface OwnershipTransferredEventObject {
  from: string;
  to: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface TransmittedEventObject {
  configDigest: string;
  epoch: number;
}
export type TransmittedEvent = TypedEvent<
  [string, number],
  TransmittedEventObject
>;

export type TransmittedEventFilter = TypedEventFilter<TransmittedEvent>;

export interface OCR2BaseUpgradeable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OCR2BaseUpgradeableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    latestConfigDetails(
      overrides?: CallOverrides
    ): Promise<
      [number, number, string] & {
        configCount: number;
        blockNumber: number;
        configDigest: string;
      }
    >;

    latestConfigDigestAndEpoch(
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, number] & {
        scanLogs: boolean;
        configDigest: string;
        epoch: number;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    setConfig(
      _signers: PromiseOrValue<string>[],
      _transmitters: PromiseOrValue<string>[],
      _f: PromiseOrValue<BigNumberish>,
      _onchainConfig: PromiseOrValue<BytesLike>,
      _offchainConfigVersion: PromiseOrValue<BigNumberish>,
      _offchainConfig: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transmit(
      reportContext: [
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>
      ],
      report: PromiseOrValue<BytesLike>,
      rs: PromiseOrValue<BytesLike>[],
      ss: PromiseOrValue<BytesLike>[],
      rawVs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transmitters(overrides?: CallOverrides): Promise<[string[]]>;

    typeAndVersion(overrides?: CallOverrides): Promise<[string]>;
  };

  acceptOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  latestConfigDetails(
    overrides?: CallOverrides
  ): Promise<
    [number, number, string] & {
      configCount: number;
      blockNumber: number;
      configDigest: string;
    }
  >;

  latestConfigDigestAndEpoch(
    overrides?: CallOverrides
  ): Promise<
    [boolean, string, number] & {
      scanLogs: boolean;
      configDigest: string;
      epoch: number;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  setConfig(
    _signers: PromiseOrValue<string>[],
    _transmitters: PromiseOrValue<string>[],
    _f: PromiseOrValue<BigNumberish>,
    _onchainConfig: PromiseOrValue<BytesLike>,
    _offchainConfigVersion: PromiseOrValue<BigNumberish>,
    _offchainConfig: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transmit(
    reportContext: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ],
    report: PromiseOrValue<BytesLike>,
    rs: PromiseOrValue<BytesLike>[],
    ss: PromiseOrValue<BytesLike>[],
    rawVs: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transmitters(overrides?: CallOverrides): Promise<string[]>;

  typeAndVersion(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    latestConfigDetails(
      overrides?: CallOverrides
    ): Promise<
      [number, number, string] & {
        configCount: number;
        blockNumber: number;
        configDigest: string;
      }
    >;

    latestConfigDigestAndEpoch(
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, number] & {
        scanLogs: boolean;
        configDigest: string;
        epoch: number;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    setConfig(
      _signers: PromiseOrValue<string>[],
      _transmitters: PromiseOrValue<string>[],
      _f: PromiseOrValue<BigNumberish>,
      _onchainConfig: PromiseOrValue<BytesLike>,
      _offchainConfigVersion: PromiseOrValue<BigNumberish>,
      _offchainConfig: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transmit(
      reportContext: [
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>
      ],
      report: PromiseOrValue<BytesLike>,
      rs: PromiseOrValue<BytesLike>[],
      ss: PromiseOrValue<BytesLike>[],
      rawVs: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    transmitters(overrides?: CallOverrides): Promise<string[]>;

    typeAndVersion(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ConfigSet(uint32,bytes32,uint64,address[],address[],uint8,bytes,uint64,bytes)"(
      previousConfigBlockNumber?: null,
      configDigest?: null,
      configCount?: null,
      signers?: null,
      transmitters?: null,
      f?: null,
      onchainConfig?: null,
      offchainConfigVersion?: null,
      offchainConfig?: null
    ): ConfigSetEventFilter;
    ConfigSet(
      previousConfigBlockNumber?: null,
      configDigest?: null,
      configCount?: null,
      signers?: null,
      transmitters?: null,
      f?: null,
      onchainConfig?: null,
      offchainConfigVersion?: null,
      offchainConfig?: null
    ): ConfigSetEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferRequested(address,address)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): OwnershipTransferRequestedEventFilter;
    OwnershipTransferRequested(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): OwnershipTransferRequestedEventFilter;

    "OwnershipTransferred(address,address)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Transmitted(bytes32,uint32)"(
      configDigest?: null,
      epoch?: null
    ): TransmittedEventFilter;
    Transmitted(configDigest?: null, epoch?: null): TransmittedEventFilter;
  };

  estimateGas: {
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    latestConfigDetails(overrides?: CallOverrides): Promise<BigNumber>;

    latestConfigDigestAndEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    setConfig(
      _signers: PromiseOrValue<string>[],
      _transmitters: PromiseOrValue<string>[],
      _f: PromiseOrValue<BigNumberish>,
      _onchainConfig: PromiseOrValue<BytesLike>,
      _offchainConfigVersion: PromiseOrValue<BigNumberish>,
      _offchainConfig: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transmit(
      reportContext: [
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>
      ],
      report: PromiseOrValue<BytesLike>,
      rs: PromiseOrValue<BytesLike>[],
      ss: PromiseOrValue<BytesLike>[],
      rawVs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transmitters(overrides?: CallOverrides): Promise<BigNumber>;

    typeAndVersion(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    latestConfigDetails(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    latestConfigDigestAndEpoch(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setConfig(
      _signers: PromiseOrValue<string>[],
      _transmitters: PromiseOrValue<string>[],
      _f: PromiseOrValue<BigNumberish>,
      _onchainConfig: PromiseOrValue<BytesLike>,
      _offchainConfigVersion: PromiseOrValue<BigNumberish>,
      _offchainConfig: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transmit(
      reportContext: [
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>,
        PromiseOrValue<BytesLike>
      ],
      report: PromiseOrValue<BytesLike>,
      rs: PromiseOrValue<BytesLike>[],
      ss: PromiseOrValue<BytesLike>[],
      rawVs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transmitters(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    typeAndVersion(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
